name: Rails
on:
  - push
  - workflow_dispatch

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_WITHOUT: development
      SECRET_KEY_BASE: ad4d97aef89588c346638cfe689f667f06bc29d2c40724107558e5d4defe723e42cfb294cdb25d7e3241195cfb7cc952e8a2c1680460bea4904bd79d21784307
      STEAM_API_KEY: abcd1234
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: citadel
          POSTGRES_PASSWORD: citadel
        ports: ["5432:5432"]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -yqq install libpq-dev libyaml-dev build-essential libcurl4-openssl-dev imagemagick
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.6
        bundler-cache: true
    - name: Setup database
      env:
        RAILS_ENV: test
        PGHOST: localhost
      run: |
        cp config/database.yml.github config/database.yml
        bundle exec rake "parallel:setup"
    - name: Run tests
      env:
        RAILS_ENV: test
        PGHOST: localhost
      run: bundle exec rake test
